# Licensed under a 3-clause BSD style license - see LICENSE.rst


from .nustarclock import *
from .utils import *
from .barycorr import *

__all__ = ["__version__"]
# NOTE: First try _version if it exists and was generated by setuptools_scm
# This file provides the version for the package.
try:
    from ._version import version
except ImportError:
    import warnings

    warnings.warn(
        f'could not determine {__name__.split(".")[0]} package version; '
        'this indicates a broken installation'
    )
    del warnings

    version = '0.0.0'

__version__ = version
